name: action

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./zoom
    
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v2
      
      - name: "Setup Go"
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      
      - name: "Test"
        run: go test -v
